### ISSUE TITLE
Got Error "(Timeout expired while executing transaction)" when I instantiate chaincode 

### ISSUE THREAD

**Issue by CocoaWang** [dongmingh/v1performance#13]
When I instantiate a new chaincode , I got errors  like following .
![image](https://user-images.githubusercontent.com/15904918/28058889-cf6b5b2a-6654-11e7-937b-7c8e78882140.png)
And from my peer-log ,I see errors like this .
![image](https://user-images.githubusercontent.com/15904918/28058924-eb6f4da4-6654-11e7-9cd1-debdbdf1d112.png)

**Comment by CocoaWang** [comment]
@dongmingh  @wshbob  How to fix this issue?

**Comment by dongmingh** [comment]
Is there any existing docker chaincode images from previous run?  If so, you need to remove those docker images.

**Comment by dongmingh** [comment]
Is this still an issue? or resolve?  Please close if resolved. Thx.

**Comment by CocoaWang** [comment]
@dongmingh resolved. Thx.
