### ISSUE TITLE
PTE result formation

### ISSUE THREAD

**Issue by z21921** [dongmingh/v1performance#14]
We got different  message from  PTE info:
info: [PTE main]: stdout: info: [PTE exec]: [Nid:chan:org:id=0:mychannel1:org2:0 invoke_query_simple] completed 100 Invoke(Move) in 4719 ms, timestamp: start 1500268105623 end 1500268110342
info: [PTE exec]: [Nid:chan:org:id=0:mychannel1:org2:5 invoke_query_simple] completed 100 Invoke(Move) in 4726 ms, timestamp: start 1500268105617 end 1500268110343

Would you format to make a same info for result? So we can calculate the performance easy. Thanks.

**Comment by dongmingh** [comment]
This is caused by the run time variation, not something I have control.  Can you parse the performance result using in ... ms?

**Comment by dongmingh** [comment]
Worked as designed.
